import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/features/Layouts/Header/Header";
import Footer from "@/components/features/Layouts/Footer/Footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });
  
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Toaster closeButton duration={3000} richColors/>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
