import styles from "./page.module.scss";

export default function Home() {
  return (
    <main className={styles.main}>
      <h1 className={styles.title}>Create Next App</h1>
      <p className={styles.description}>Generated by create next app</p>
    </main>
  );
}
